[package]
name = "cyberstride-py"
description = "Python bindings for cyberstride-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
cyberstride-core = { path = "../cyberstride-core" }
pyo3 = { workspace = true }
numpy = { workspace = true }
